### ISSUE TITLE
Ein paar Anmerkungen

### ISSUE THREAD

**Issue by blechert** [Silas11/Silas11.github.io#2]
- Du vermischst bei Deinen Texten Deutsch und Englisch. Entscheide Dich für eine Sprache und ziehe das durch. Ansonsten sieht das irgendwie komisch aus.
- Hintergrundfarbe der Seiten nicht einheitlich. Du hast eine zentrale CSS Datei. Nutze sie. :-)
- Die Dropdown Box über der Karte ("Euopa Cities", ...) macht nicht. Sollteste auskommentieren oder mit "leben" versorgen.
- Guck Dir meinen Pull Request an: https://github.com/Silas11/Silas11.github.io/pull/1

**Comment by Silas11** [comment]
Dankeschön !
